modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "${issues_link}"
license = "MIT"

[[mods]]
modId = "mob_armor_trims"
version = "${version}"
displayName = "Mob Armor Trims"
authors = "majo24"
description = "${mod_description}"
logoFile = "assets/mob_armor_trims/icon.png"

[[dependencies.mob_armor_trims]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mob_armor_trims]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mob_armor_trims]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mob_armor_trims]]
modId = "cloth_config"
mandatory = false
versionRange = "[${cloth_config_api_version},)"
ordering = "AFTER"
side = "CLIENT"
