package net.majo24.mob_armor_trims.config;

import net.majo24.mob_armor_trims.config.backend.annotations.Entry;
import net.majo24.mob_armor_trims.config.backend.annotations.SubConfig;
import net.majo24.mob_armor_trims.config.backend.entries.BlacklistEntry;
import net.majo24.mob_armor_trims.trim_combinations_system.CustomTrim;
import net.majo24.mob_armor_trims.trim_combinations_system.TrimCombination;
import net.majo24.mob_armor_trims.config.backend.entries.PrimitiveEntry;
import net.majo24.mob_armor_trims.config.backend.entries.TrimCombinationsEntry;
import net.majo24.mob_armor_trims.config.backend.entries.TrimSystemEntry;
import net.minecraft.core.RegistryAccess;
import net.minecraft.world.item.equipment.trim.*;
import org.jetbrains.annotations.Nullable;

import java.util.*;

public class Config {
    private final Map<List<String>, ArmorTrim> cachedCustomTrims = new HashMap<>();

    /**
     * @param requiredMaterial The material the trim combination has to match
     * @return A random trim combination that matches the given required material. Null if no trim combination matches.
     */
    @Nullable
    public TrimCombination getRandomTrimCombination(String requiredMaterial) {
        List<TrimCombination> trimCombinations = this.customTrimCombinations.trimCombinations.getTrimCombinations();

        if (!trimCombinations.isEmpty()) {
            Collections.shuffle(trimCombinations);
            for (TrimCombination trimCombination : trimCombinations) {
                if (trimCombination.materialToApplyTo().equals(requiredMaterial)) {
                    return trimCombination;
                }
            }
        }

        return null;
    }

    @Nullable
    public ArmorTrim getOrCreateCachedTrim(String material, String pattern, RegistryAccess registryAccess) {
        ArmorTrim trim = this.cachedCustomTrims.get(Arrays.asList(material, pattern));

        if (trim == null) {
            trim = new CustomTrim(material, pattern).getTrim(registryAccess);
            if (trim == null) return null;

            this.cachedCustomTrims.put(Arrays.asList(material, pattern), trim);
        }

        return trim;
    }


    @SubConfig(name = "general", description = "General Settings for the mod")
    public final GeneralSubConfig general = new GeneralSubConfig();

    @SubConfig(name = "random_trims", description = "Settings for the Random Trims backend.\nThese settings will only make a difference, if the RANDOM_TRIMS backend is enabled")
    public final RandomTrimsSubConfig randomTrims = new RandomTrimsSubConfig();

    @SubConfig(name = "trim_combinations", description = "Settings for the Custom Trim Combinations backend.\nThese settings will only make a difference, if the CUSTOM_TRIM_COMBINATIONS backend is enabled")
    public final TrimCombinationsSubConfig customTrimCombinations = new TrimCombinationsSubConfig();

    public static final class GeneralSubConfig {
        @SubConfig(name = "trim_mobs", description = "Settings for trimming a mobs equipment")
        public final TrimMobsSubConfig trimMobs = new TrimMobsSubConfig();

        @SubConfig(name = "trim_loot_tables", description = "Settings for trimming items generated by loot tables")
        public final TrimLootTablesSubConfig trimLootTables = new TrimLootTablesSubConfig();

        @SubConfig(name = "trim_trades", description = "Settings for trimming villager trades")
        public final TrimTradesSubConfig trimTrades = new TrimTradesSubConfig();

        public static class TrimMobsSubConfig {
            @Entry(name = "enabled_system", description = """
                    Select the System of how to select, what trims to give mobs.
                    - RANDOM_TRIMS: Randomly choose the trim, but also take the previous trim highly into account.
                    - CUSTOM_TRIMS: Choose the trim from a list of custom trims. You can manage the trims yourself""")
            public final TrimSystemEntry enabledSystem = new TrimSystemEntry(TrimSystems.RANDOM_TRIMS);

            @Entry(name = "no_trims_chance", description = "Chance of the mob having no trims at all")
            public final PrimitiveEntry<Integer> noTrimsChance = new PrimitiveEntry<>(25);
        }

        public static class TrimLootTablesSubConfig {
            @Entry(name = "trim_chance", description = "Chance of an item generated by a loot table of having a trim applied")
            public final PrimitiveEntry<Integer> trimChance = new PrimitiveEntry<>(50);
        }

        public static class TrimTradesSubConfig {
            @Entry(name = "trim_chance", description = "Chance of a trade of having a trim applied")
            public final PrimitiveEntry<Integer> trimChance = new PrimitiveEntry<>(50);

            @Entry(name = "min_level", description = "The minimum villager trading level a item needs to be in, to have a chance of being trimmed")
            public final PrimitiveEntry<Integer> minLevel = new PrimitiveEntry<>(3);
        }
    }

    public static final class RandomTrimsSubConfig {
        @Entry(name = "trim_chance", description = "Chance of each armor piece from a mob having an armor trim")
        public final PrimitiveEntry<Integer> trimChance = new PrimitiveEntry<>(75);

        @Entry(name = "similar_trim_chance", description = "Chance of each armor piece having a similar armor trim as the previous armor piece")
        public final PrimitiveEntry<Integer> similarTrimChance = new PrimitiveEntry<>(75);

        @Entry(name = "blacklist", description = "Blacklist for trim patterns.\nThis uses regex. This means, if you want to check for a specific pattern, you need to use \"^[pattern$]\" instead of just \"[pattern]\".\nBy default, all patterns from the Trimmable Tools mod are blacklisted, since they only work for tools and not armor.")
        public final BlacklistEntry blacklist = new BlacklistEntry(List.of("^tooltrims:.*"));
    }

    public static final class TrimCombinationsSubConfig {
        @Entry(name = "custom_trim_combinations", description = """
                The list of custom trim combinations.
                
                To create a new trim combination, add a new list with with 5 lists inside.
                Then for the first inner list, add a String. In the rest of the inner lists, add 2 Strings.
                It should look somewhat like this: [[""], ["", ""], ["", ""], ["", ""], ["", ""]]
                Make sure to have the outer list separated with a comma from other trim combinations.
                
                In the first lists String, enter the Armor Material, the trim combination should be applied on.
                For example: ["gold"]
                
                For the rest of the lists, in the first String, enter a valid Trim Material.
                In the second String, enter a valid Trim Pattern
                To not have to specify the whole trim pattern, you can leave out the "_armor_trim_smithing_template" part of the pattern, as it is the same for every pattern.
                For example: ["amethyst_shard", "silence"]""")
        public final TrimCombinationsEntry trimCombinations = new TrimCombinationsEntry(new ArrayList<>());
    }

    public enum TrimSystems {
        RANDOM_TRIMS,
        CUSTOM_TRIM_COMBINATIONS,
        NONE,
    }
}
