# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod.name=Naturally Trimmed
mod.id=naturally_trimmed
mod.group=net.majo24
mod.version=3.5.0
mod.description=Trims naturally generated armor and equipment from mobs, loot tables and trades
mod.github_link=https://github.com/Imajo24I/Naturally-Trimmed
mod.issues_link=https://github.com/Imajo24I/Naturally-Trimmed/issues/new/choose

# Static dependencies
deps.fabric_loader=0.18.5
deps.quilt_parser=0.3.1
