["26.1"]
mc.dep = "~26.1"
mc.targets = "26.1, 26.1.1, 26.1.2"

#deps.parchment | No version available
deps.yacl = "3.9.1+26.1"

["26.1-fabric"]
deps.fabric_api = "0.143.12+26.1"
deps.modmenu = "18.0.0-alpha.6"

["26.1-neoforge"]
deps.neoforge = "26.1.0.1-beta"

["1.21.11"]
mc.dep = ">=1.21.11 <=1.21.11"
mc.targets = "1.21.11"

deps.parchment = "2025.12.20"
deps.yacl = "3.8.1+1.21.11"

["1.21.11-fabric"]
deps.fabric_api = "0.139.4+1.21.11"
deps.modmenu = "17.0.0-alpha.1"

["1.21.11-neoforge"]
deps.neoforge = "21.11.0-beta"

["1.21.1"]
mc.dep = "1.21.1"
mc.targets = "1.21.1"

deps.parchment = "2024.11.17"
deps.yacl = "3.6.6+1.21.1"

["1.21.1-fabric"]
deps.fabric_api = "0.116.10+1.21.1"
deps.modmenu = "11.0.4"

["1.21.1-neoforge"]
deps.neoforge = "21.1.224"