modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues_link}"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "majo24"
description = "${description}"
logoFile = "assets/mob_armor_trims/icon.png"

[["dependencies.${id}"]]
modId = "${forge_id}"
mandatory = true
versionRange = "${forgeConstraint}"
ordering = "NONE"
side = "BOTH"

[["dependencies.${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${mcdep}"
ordering = "NONE"
side = "BOTH"

[["dependencies.${id}"]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[${yacl_version},)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config="mob_armor_trims.mixins.json"
