name: Bug Report
description: Create a bug report.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |-
        ### Before posting an issue
        - Make sure this and other relevant mods are up-to-date
        - Make sure this issue hasn't already been reported
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Use this section to describe the issue you are experiencing in as
        much depth as possible.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Provide as much information as possible on how to reproduce this
        bug. Make sure your instructions are as clear and concise as possible-
  - type: textarea
    id: log
    attributes:
      label: Log File and Crash Report
      description: Provide at least the log file here. If one has been created
      placeholder: >-
        Drag-and-Drop the log file or crash report here.

        You can find the log file inside the  `.minecraft/logs` folder. Most
        often, you will want the `latest.log` file, since that file belongs to
        the last played session of the game.
    validations:
      required: true
