name: Feature Request
description: Suggest an additional feature to add to this project
labels: [feature request]
body:
  - type: textarea
    attributes:
      label: Feature description.
      description: A clear and concise description of what the feature should be.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false


  - type: textarea
    attributes:
      label: Additional Context.
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
