package net.majo24.naturally_trimmed.config;

import com.google.gson.*;
import net.majo24.naturally_trimmed.NaturallyTrimmed;
import net.majo24.naturally_trimmed.config.core.Entry;
import net.majo24.naturally_trimmed.config.core.ManagedConfig;
import net.majo24.naturally_trimmed.config.core.Schema;
import net.majo24.naturally_trimmed.config.core.SubConfig;
import net.majo24.naturally_trimmed.trim_application.TrimData;
import net.minecraft.world.item.equipment.trim.*;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

@Schema(1)
public class Config extends ManagedConfig<Config> {
    private static final Map<Type, Object> typeAdapters = new HashMap<>() {{
        put(FilterRule.class, new FilterRuleTypeAdapter<>());
    }};

    public static final Config DEFAULT;
    public static final Config INSTANCE;

    static {
        DEFAULT = new Config(null);
        DEFAULT.setDefaultGetter(() -> DEFAULT);
        INSTANCE = new Config(() -> DEFAULT);
    }

    public Config(Supplier<Config> defaults) {
        super(NaturallyTrimmed.getConfigPath(), defaults, typeAdapters);
    }

    // === Config Entries ===

    @Entry(comment = "If enabled, the mod will try to apply trims to the equipment of mobs when they're newly spawning.")
    public boolean enableTrimMobs = true;

    @Entry(comment = """
            If enabled, the mod will try to apply trims to equipment generated by loot tables.
            This includes chests or other containers, mob drops and more.
            """)
    public boolean enableTrimLootTables = true;

    @Entry(comment = """
            If enabled, the mod will try to apply trims to equipment of trades.
            This includes villager trades like a diamond chestplate from armorer villagers, trades from wandering traders or modded trader mobs.
            """)
    public boolean enableTrimTrades = true;

    @SubConfig(comment = "Settings for determining/filtering which trims can be used by the mod")
    public TrimFilteringSubConfig trimFiltering = new TrimFilteringSubConfig();

    @SubConfig(comment = "Settings for trimming a mob's equipment")
    public TrimMobsSubConfig trimMobs = new TrimMobsSubConfig();

    @SubConfig(comment = "Settings for trimming equipment generated by loot tables")
    public TrimLootTablesSubConfig trimLootTables = new TrimLootTablesSubConfig();

    @SubConfig(comment = "Settings for trimming equipment from villager trades")
    public TrimTradesSubConfig trimTrades = new TrimTradesSubConfig();

    // === Sub Configs ===

    public static class TrimFilteringSubConfig {
        @Entry(comment = """
                Enables filtering trims by checking for the corresponding textures of the trim.
                However, this only works on the client, it will be not be applied on dedicated servers, due to textures not being available on dedicated servers.
                
                See 'https://github.com/Imajo24I/Naturally-Trimmed/wiki/Config-%E2%80%90-3.5.0#texture-validation-filtering'
                
                When this setting *is* applied (on client + enabled), it will override some built-in filtering (none of the other trim filtering config entries!).
                """)
        public boolean textureValidationFiltering = true;

        @Entry(comment = "Use only vanilla trim materials and patterns")
        public boolean vanillaOnly = false;

        @Entry(comment = """
                Filter trim materials.
                
                See 'https://github.com/Imajo24I/Naturally-Trimmed/wiki/Config-‐-3.5.0#trim-material-filter--material_filter' for documentation on this.
                
                Example configuration, blacklisting everything but biomes_o_plenty's trim materials and all trim materials that have the c:gold tag:
                materialFilter: ["+biomes_o_plenty:.*", "+#c:gold", "-.*"]
                """)
        public List<FilterRule<TrimMaterial>> materialFilter = new ArrayList<>();

        @Entry(comment = """
                Filter trim patterns.
                
                See 'https://github.com/Imajo24I/Naturally-Trimmed/wiki/Config-‐-3.5.0#trim-pattern-filter--pattern_filter' for documentation on this.
                
                Example configuration, blacklisting everything but the silence trim pattern
                patternFilter: ["+minecraft:silence", "-.*"]
                """)
        public List<FilterRule<TrimPattern>> patternFilter = List.of(FilterRule.construct("-tooltrims:.*", false));
    }

    public static class TrimMobsSubConfig {
        @Entry(comment = """
                Select the trim system. Trim systems define how the mod chooses what trims to use.
                - RANDOM_TRIMS: Randomly chooses the trim to apply to the mob. Filtering from 'trimFiltering' applies to this.
                - PREDEFINED_TRIMS: Chooses the trim from a list of predefined trims. See 'predefinedTrims'. Filtering from 'trimFiltering' doesn't apply to this.""")
        public TrimSystem trimSystem = TrimSystem.RANDOM_TRIMS;

        @Entry(comment = "Chance of the mob having no trims at all")
        public int noTrimsChance = 25;

        @Entry(comment = "Chance of each equipment piece having a trim applied. Applies individually to each armor piece.")
        public int trimChance = 75;

        @Entry(comment = """
                List of predefined trims.
                
                See 'trimSystem'.
                A predefined trim consists of a trim material and a trim pattern.
                The mod randomly selects a predefined trim to use out of this list.
                
                Example configuration:
                predefinedTrims: [{material: "resin", pattern: "silence"}, {material: "netherite", pattern: "vex"}, {material: "minecraft:amethyst", pattern: "minecraft:silence"}]
                """)
        public List<TrimData> predefinedTrims = new ArrayList<>();

        public enum TrimSystem {
            RANDOM_TRIMS,
            PREDEFINED_TRIMS,
        }
    }

    public static class TrimLootTablesSubConfig {
        @Entry(comment = "Chance of an item generated by a loot table having a trim applied")
        public int trimChance = 50;
    }

    public static class TrimTradesSubConfig {
        @Entry(comment = "Chance of an item from a villager trade having a trim applied")
        public int trimChance = 50;

        @Entry(comment = "The minimum villager trading level an item needs to be in, to be considered of being trimmed")
        public int minLevel = 3;
    }

    // === Misc Stuff ===

    /// Will be triggered for schema version migration after any successful load from file
    public void migrateSchema() {
        boolean saveAfter = this._version != DEFAULT._version;

        if (this._version < 1) {
            this._version = 1;
        }

        if (saveAfter) {
            this.saveToFile();
        }
    }

    public static class FilterRuleTypeAdapter<T> implements JsonSerializer<FilterRule<T>>, JsonDeserializer<FilterRule<T>> {
        @Override
        public JsonElement serialize(FilterRule src, Type type, JsonSerializationContext jsonSerializationContext) {
            return new JsonPrimitive(src.toString());
        }

        @Override
        public FilterRule<T> deserialize(JsonElement json, Type type, JsonDeserializationContext jsonDeserializationContext) throws JsonParseException {
            return FilterRule.construct(json.getAsString(), ((ParameterizedType) type).getActualTypeArguments()[0] == TrimMaterial.class);
        }
    }
}
