package net.majo24.naturally_trimmed.config;

import net.majo24.naturally_trimmed.NaturallyTrimmed;
import net.majo24.naturally_trimmed.config.backend.ConfigManager;
import net.majo24.naturally_trimmed.config.backend.Entry;
import net.majo24.naturally_trimmed.config.backend.SubConfig;
import net.majo24.naturally_trimmed.trim_application.TrimData;
import net.minecraft.world.item.equipment.trim.*;

import java.util.ArrayList;
import java.util.List;

public class Config {
    public static final ConfigManager<Config> CONFIG_MANAGER = new ConfigManager<>(Config.class, NaturallyTrimmed.getConfigPath());

    // === Config Entries ===

    @Entry(name = "enable_trim_mobs", comment = "Enables the equipment from mobs to be trimmed")
    public boolean enableTrimMobs = true;

    @Entry(name = "enable_trim_loot_tables", comment = "Enables the equipment generated by loot tables to be trimmed")
    public boolean enableTrimLootTables = true;

    @Entry(name = "enable_trim_trades", comment = "Enables the equipment from villager trades to be trimmed")
    public boolean enableTrimTrades = true;

    @Entry(name = "texture_validation_filtering", comment = """
            Enables filtering trims by checking for the corresponding textures of the trim.
            This is the best filtering method, since it directly checks for the textures.
            For more info about missing-texture trims, see the mods description.
            
            However, this only works on the client, it will be not be applied on dedicated servers, due to textures not being available on serverside.
            When this setting *is* applied (on client + enabled), it will override all other filtering,
            including the vanillaOnly setting, the blacklists and the built-in trim filtering, as these will become unnecessary.
            """)
    public boolean textureValidationFiltering = true;

    @Entry(name = "vanilla_only", comment = """
            Use and filter for vanilla-only trim materials and patterns.
            
            Other than mod customization, this can also be used as to easily filter no-texture trims, when the texture_validation_filtering isn't available.
            For more info about missing-texture trims, see the mods description.
            For more advanced workarounds and customization, without having to blacklist all non-vanilla trims, see material_blacklist and pattern_blacklist.
            """)
    public boolean vanillaOnly = false;

    @Entry(name = "material_filter", comment = """
            Filter trim materials.
            
            See https://github.com/Imajo24I/Naturally-Trimmed/wiki/Config#trim-material-filter--material_filter for documentation on this.
            
            Example configuration, blacklisting everything but biomes_o_plenty's trim materials and all trim materials that have the c:gold tag:
            material_filter: ["+biomes_o_plenty:.*", "+#c:gold", "-.*"],
            """)
    public List<FilterRule<TrimMaterial>> materialFilter = new ArrayList<>();

    @Entry(name = "pattern_filter", comment = """
            Filter trim patterns.
            
            See https://github.com/Imajo24I/Naturally-Trimmed/wiki/Config#trim-pattern-filter--pattern_filter for documentation on this.
            
            Example configuration, blacklisting everything but the silence trim pattern
            pattern_filter: ["+minecraft:silence", "-.*"],
            """)
    public List<FilterRule<TrimPattern>> patternFilter = List.of(FilterRule.construct("-tooltrims:.*", false));

    @SubConfig(name = "trim_mobs", comment = "Settings for trimming a mob's equipment")
    public TrimMobsSubConfig trimMobs = new TrimMobsSubConfig();

    @SubConfig(name = "trim_loot_tables", comment = "Settings for trimming equipment generated by loot tables")
    public TrimLootTablesSubConfig trimLootTables = new TrimLootTablesSubConfig();

    @SubConfig(name = "trim_trades", comment = "Settings for trimming equipment from villager trades")
    public TrimTradesSubConfig trimTrades = new TrimTradesSubConfig();

    // === Sub Configs ===

    public static class TrimMobsSubConfig {
        @Entry(name = "trim_system", comment = """
                Select the trim system. Trim systems define how the mod chooses what trims to use.
                - RANDOM_TRIMS: Randomly chooses the trim to apply to the mob.
                - PREDEFINED_TRIMS: Chooses the trim from a list of predefined trims. You can manage the list of trims under the predefined_trims config entry.""")
        public TrimSystem trimSystem = TrimSystem.RANDOM_TRIMS;

        @Entry(name = "no_trims_chance", comment = "Chance of the mob having no trims at all")
        public int noTrimsChance = 25;

        @Entry(name = "trim_chance", comment = "Chance of each individual armor piece having a trim")
        public int trimChance = 75;

        @Entry(name = "predefined_trims", comment = """
                List of predefined trims.
                
                A predefined trim consists of a trim material and a trim pattern.
                
                Example configuration:
                predefined_trims: [{material: "resin", pattern: "silence"}, {material: "netherite", pattern: "vex"}, {material: "minecraft:amethyst", pattern: "minecraft:silence"}]
                """)
        public List<TrimData> predefinedTrims = new ArrayList<>();

        public enum TrimSystem {
            RANDOM_TRIMS,
            PREDEFINED_TRIMS,
        }
    }

    public static class TrimLootTablesSubConfig {
        @Entry(name = "trim_chance", comment = "Chance of an item generated by a loot table of having a trim applied")
        public int trimChance = 50;
    }

    public static class TrimTradesSubConfig {
        @Entry(name = "trim_chance", comment = "Chance of a villager trade of having a trim applied")
        public int trimChance = 50;

        @Entry(name = "min_level", comment = "The minimum villager trading level an item needs to be in, to have a chance of being trimmed")
        public int minLevel = 3;
    }
}
