modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues_link}"
license = "MIT"

[[mods]]
modId = "mob_armor_trims"
version = "${version}"
displayName = "Mob Armor Trims"
authors = "majo24"
description = "${mod_description}"
logoFile = "assets/mob_armor_trims/icon.png"

[[dependencies.mob_armor_trims]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mob_armor_trims]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mob_armor_trims]]
modId = "cloth_config"
type = "optional"
reason = "Cloth Config API is highly recomennded, as it is required to configure this mod through the Config Menu of Neoforge."
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "mob_armor_trims.mixins.json"
