name: Publish on GitHub, CurseForge & Modrinth

on: [workflow_dispatch]

env:
  MINECRAFT_VERSON: 1.20.6
  JAVA_VERSION: 21
  MOD_VERSION: 1.0.4
  RELEASE_NAME: Mob Armor Trims

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Enviroment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradlew Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      # MC Publish stuff
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1005441
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: hHVaPgFK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: "v${{env.VERSION}}"
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
          files: build/libs/!(*-@(dev|sources|javadoc)).jar